version: '3.8'
services:
  # Nombre del servicio
  postgres:
    # Imagen oficial de Docker Hub
    image: postgres:16-alpine
    # Mapea el puerto 5432 del contenedor al puerto 5432 de tu m치quina.
    ports:
      - '5432:5432'
    # Variables de entorno para la configuraci칩n de la DB
    environment:
      # Nombre de la base de datos que crear치
      POSTGRES_DB: nest_db
      # Usuario de la base de datos
      POSTGRES_USER: nest_user
      # Contrase침a del usuario
      POSTGRES_PASSWORD: nest_password
    # Reinicia si falla
    restart: always
